general:
  profile_name: default
  language: pt-BR
  timezone: America/Sao_Paulo
  wake_words:
  - hey gem
  - oi gem
  - gem
  response_delay: 0.5
  auto_save: true
  privacy_mode: true
  offline_mode: true
  debug_mode: false
audio:
  sample_rate: 16000
  channels: 1
  chunk_size: 1024
  device_index: null
  input_device: null
  output_device: null
  noise_reduction: true
  echo_cancellation: true
  auto_gain_control: true
  volume_threshold: 0.01
  silence_timeout: 2.0
stt:
  engine: whisper
  model: base
  language: pt-BR
  energy_threshold: 300
  dynamic_energy_threshold: true
  pause_threshold: 0.8
  phrase_threshold: 0.3
  non_speaking_duration: 0.5
tts:
  engine: pyttsx3
  voice: null
  rate: 150
  volume: 0.9
  language: pt-BR
  gender: female
  age: adult
llm:
  provider: ollama
  model: phi3:mini
  base_url: http://localhost:11434
  api_key: null
  temperature: 0.7
  max_tokens: 1000
  context_length: 4096
  system_prompt: Você é o GEM, um assistente de voz acessível e amigável.
accessibility:
  screen_reader_support: true
  high_contrast_mode: false
  large_text_mode: false
  voice_commands_only: false
  slow_speech_mode: false
  repeat_confirmations: true
  audio_descriptions: true
  keyboard_navigation: true
health:
  medication_reminders: true
  exercise_reminders: true
  hydration_reminders: true
  posture_reminders: true
  break_reminders: true
  sleep_tracking: false
  mood_tracking: false