#!/bin/bash
# Setup API keys for enhanced development

echo "🔑 GEM OS API Key Setup"
echo "Please visit these links to get your free API keys:"
echo ""
echo "🤖 AI Providers:"
echo "- GitHub Copilot: https://github.com/features/copilot (Free with Student Pack)"
echo "- Microsoft Copilot: https://copilot.microsoft.com/ (Free with Student Account)"
echo "- Google Gemini: https://makersuite.google.com/app/apikey (Free tier available)"
echo "- Anthropic Claude: https://console.anthropic.com/ (Free tier available)"
echo ""
echo "📚 Education:"
echo "- DataCamp: https://www.datacamp.com/students (50% off with student email)"
echo "- Skillshare: https://www.skillshare.com/student (30% off)"
echo ""
echo "💚 Health & Wellness:"
echo "- Calm: https://www.calm.com/students (Free 30 days)"
echo "- Headspace: https://www.headspace.com/students (85% off)"
echo ""
echo "📋 Productivity:"
echo "- Notion: https://www.notion.so/students (Free for students)"
echo "- Microsoft 365: https://www.microsoft.com/education/students (Free)"
echo ""
echo "☁️ Cloud:"
echo "- AWS Educate: https://aws.amazon.com/education/awseducate/"
echo "- Azure for Students: https://azure.microsoft.com/free/students/"
echo ""
echo "After getting your keys, copy .env.template to .env and fill them in!"
