jobs:
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: echo 'Deploying GEM OS'
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - run: pip install -r requirements.txt
    - run: python -m pytest tests/
    - run: python gem.py --test
name: GEM OS CI/CD
'on':
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
