name: Override Dependency Submission

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

env:
  ACTIONS_RUNNER_DEBUG: true
  ACTIONS_STEP_DEBUG: true

jobs:
  override:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Override automatic dependency submission
      run: |
        echo "Overriding automatic dependency submission"
        echo "GH_DEPENDENCY_SUBMISSION_SKIP_CACHE=true" >> $GITHUB_ENV
        echo "SKIP_DEPENDENCY_SUBMISSION=true" >> $GITHUB_ENV
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip'
        cache-dependency-path: 'requirements.txt'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Success
      run: echo "✅ Workflow completed successfully"
